//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ProbaKursacha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Cотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Cотрудник CustomAttributes)

    // *** End programmer edit section *** (Cотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CотрудникE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРожд as \'Дата рожд\'",
            "Телефон as \'Телефон\'",
            "СерНомПаспорта as \'Сер ном паспорта\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("CотрудникE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("CотрудникL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРожд as \'Дата рожд\'",
            "Телефон as \'Телефон\'",
            "СерНомПаспорта as \'Сер ном паспорта\'",
            "Должность.Наименование as \'Наименование\'"})]
    public class Cотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private System.DateTime fДатаРожд;
        
        private int fТелефон;
        
        private int fСерНомПаспорта;
        
        private IIS.ProbaKursacha.Должность fДолжность;
        
        // *** Start programmer edit section *** (Cотрудник CustomMembers)

        // *** End programmer edit section *** (Cотрудник CustomMembers)

        
        /// <summary>
        /// ДатаРожд.
        /// </summary>
        // *** Start programmer edit section *** (Cотрудник.ДатаРожд CustomAttributes)

        // *** End programmer edit section *** (Cотрудник.ДатаРожд CustomAttributes)
        public virtual System.DateTime ДатаРожд
        {
            get
            {
                // *** Start programmer edit section *** (Cотрудник.ДатаРожд Get start)

                // *** End programmer edit section *** (Cотрудник.ДатаРожд Get start)
                System.DateTime result = this.fДатаРожд;
                // *** Start programmer edit section *** (Cотрудник.ДатаРожд Get end)

                // *** End programmer edit section *** (Cотрудник.ДатаРожд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cотрудник.ДатаРожд Set start)

                // *** End programmer edit section *** (Cотрудник.ДатаРожд Set start)
                this.fДатаРожд = value;
                // *** Start programmer edit section *** (Cотрудник.ДатаРожд Set end)

                // *** End programmer edit section *** (Cотрудник.ДатаРожд Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Cотрудник.Имя CustomAttributes)

        // *** End programmer edit section *** (Cотрудник.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Cотрудник.Имя Get start)

                // *** End programmer edit section *** (Cотрудник.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Cотрудник.Имя Get end)

                // *** End programmer edit section *** (Cотрудник.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cотрудник.Имя Set start)

                // *** End programmer edit section *** (Cотрудник.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Cотрудник.Имя Set end)

                // *** End programmer edit section *** (Cотрудник.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Cотрудник.Отчество CustomAttributes)

        // *** End programmer edit section *** (Cотрудник.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Cотрудник.Отчество Get start)

                // *** End programmer edit section *** (Cотрудник.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Cотрудник.Отчество Get end)

                // *** End programmer edit section *** (Cотрудник.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cотрудник.Отчество Set start)

                // *** End programmer edit section *** (Cотрудник.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Cотрудник.Отчество Set end)

                // *** End programmer edit section *** (Cотрудник.Отчество Set end)
            }
        }
        
        /// <summary>
        /// СерНомПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Cотрудник.СерНомПаспорта CustomAttributes)

        // *** End programmer edit section *** (Cотрудник.СерНомПаспорта CustomAttributes)
        public virtual int СерНомПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Cотрудник.СерНомПаспорта Get start)

                // *** End programmer edit section *** (Cотрудник.СерНомПаспорта Get start)
                int result = this.fСерНомПаспорта;
                // *** Start programmer edit section *** (Cотрудник.СерНомПаспорта Get end)

                // *** End programmer edit section *** (Cотрудник.СерНомПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cотрудник.СерНомПаспорта Set start)

                // *** End programmer edit section *** (Cотрудник.СерНомПаспорта Set start)
                this.fСерНомПаспорта = value;
                // *** Start programmer edit section *** (Cотрудник.СерНомПаспорта Set end)

                // *** End programmer edit section *** (Cотрудник.СерНомПаспорта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Cотрудник.Телефон CustomAttributes)

        // *** End programmer edit section *** (Cотрудник.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Cотрудник.Телефон Get start)

                // *** End programmer edit section *** (Cотрудник.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Cотрудник.Телефон Get end)

                // *** End programmer edit section *** (Cотрудник.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cотрудник.Телефон Set start)

                // *** End programmer edit section *** (Cотрудник.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Cотрудник.Телефон Set end)

                // *** End programmer edit section *** (Cотрудник.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Cотрудник.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Cотрудник.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Cотрудник.Фамилия Get start)

                // *** End programmer edit section *** (Cотрудник.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Cотрудник.Фамилия Get end)

                // *** End programmer edit section *** (Cотрудник.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cотрудник.Фамилия Set start)

                // *** End programmer edit section *** (Cотрудник.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Cотрудник.Фамилия Set end)

                // *** End programmer edit section *** (Cотрудник.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Cотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Cотрудник.Должность CustomAttributes)

        // *** End programmer edit section *** (Cотрудник.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.ProbaKursacha.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Cотрудник.Должность Get start)

                // *** End programmer edit section *** (Cотрудник.Должность Get start)
                IIS.ProbaKursacha.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Cотрудник.Должность Get end)

                // *** End programmer edit section *** (Cотрудник.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cотрудник.Должность Set start)

                // *** End programmer edit section *** (Cотрудник.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Cотрудник.Должность Set end)

                // *** End programmer edit section *** (Cотрудник.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CотрудникE", typeof(IIS.ProbaKursacha.Cотрудник));
                }
            }
            
            /// <summary>
            /// "CотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CотрудникL", typeof(IIS.ProbaKursacha.Cотрудник));
                }
            }
        }
    }
}
