//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ProbaKursacha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форма регис вх.
    /// </summary>
    // *** Start programmer edit section *** (ФормаРегисВх CustomAttributes)

    // *** End programmer edit section *** (ФормаРегисВх CustomAttributes)
    [AutoAltered()]
    [Caption("Форма регис вх")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормаРегисВхE", new string[] {
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("ФормаРегисВхE", "ТчРегистВхода", "ТчРегистВходаE", true, "", "Тч регист входа", true, new string[] {
            ""})]
    [View("ФормаРегисВхL", new string[0])]
    public class ФормаРегисВх : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.ProbaKursacha.DetailArrayOfТчРегистВхода fТчРегистВхода;
        
        // *** Start programmer edit section *** (ФормаРегисВх CustomMembers)

        // *** End programmer edit section *** (ФормаРегисВх CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегисВх.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормаРегисВх.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегисВх.Дата Get start)

                // *** End programmer edit section *** (ФормаРегисВх.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормаРегисВх.Дата Get end)

                // *** End programmer edit section *** (ФормаРегисВх.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегисВх.Дата Set start)

                // *** End programmer edit section *** (ФормаРегисВх.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормаРегисВх.Дата Set end)

                // *** End programmer edit section *** (ФормаРегисВх.Дата Set end)
            }
        }
        
        /// <summary>
        /// Форма регис вх.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегисВх.ТчРегистВхода CustomAttributes)

        // *** End programmer edit section *** (ФормаРегисВх.ТчРегистВхода CustomAttributes)
        public virtual IIS.ProbaKursacha.DetailArrayOfТчРегистВхода ТчРегистВхода
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегисВх.ТчРегистВхода Get start)

                // *** End programmer edit section *** (ФормаРегисВх.ТчРегистВхода Get start)
                if ((this.fТчРегистВхода == null))
                {
                    this.fТчРегистВхода = new IIS.ProbaKursacha.DetailArrayOfТчРегистВхода(this);
                }
                IIS.ProbaKursacha.DetailArrayOfТчРегистВхода result = this.fТчРегистВхода;
                // *** Start programmer edit section *** (ФормаРегисВх.ТчРегистВхода Get end)

                // *** End programmer edit section *** (ФормаРегисВх.ТчРегистВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегисВх.ТчРегистВхода Set start)

                // *** End programmer edit section *** (ФормаРегисВх.ТчРегистВхода Set start)
                this.fТчРегистВхода = value;
                // *** Start programmer edit section *** (ФормаРегисВх.ТчРегистВхода Set end)

                // *** End programmer edit section *** (ФормаРегисВх.ТчРегистВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормаРегисВхE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаРегисВхE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаРегисВхE", typeof(IIS.ProbaKursacha.ФормаРегисВх));
                }
            }
            
            /// <summary>
            /// "ФормаРегисВхL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаРегисВхL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаРегисВхL", typeof(IIS.ProbaKursacha.ФормаРегисВх));
                }
            }
        }
    }
}
